/* Revisão editorial e geométrica de 06/10/2026. Mantém os códigos originais.
   Coordenadas em metros: rede y=0; fundo ±11,885; simples x=±4,115.
   As figuras mostram montagem inicial; não representam a execução do gesto. */
const REVISAO145 = [];
(function(){
 const ex=id=>EX.find(e=>e.id===id);
 function corrigir(id,motivo,fn){const e=ex(id);if(!e)throw new Error('Exercício ausente: '+id);const antes=JSON.stringify(e);fn(e);if(antes!==JSON.stringify(e))REVISAO145.push({id,motivo});}
 function substituir(e,a,b){for(const k of ['objetivo','montagem','execucao','erro','sucesso','dica'])if(typeof e[k]==='string')e[k]=e[k].split(a).join(b);for(const k of ['passos','foco','erros','dificultar'])e[k]=e[k].map(s=>s.split(a).join(b));Object.keys(e.prog).forEach(k=>e.prog[k]=e.prog[k].split(a).join(b));if(e.kids)e.kids=e.kids.split(a).join(b);e.fig.nota=e.fig.nota.split(a).join(b);}
 const pecas=(e,t)=>e.fig.el.filter(p=>p[0]===t);
 const livres=e=>e.fig.el.forEach(p=>{if(['aluno','colega','prof'].includes(p[0]))p[4]='esperaLivre';});
 for(const m of [{id:'rodo',nome:'Rodo de saibro'},{id:'colchonete',nome:'Colchonete para apoio dos joelhos'},{id:'cartao',nome:'Cartão de registro'}])if(!MATERIAIS.some(x=>x.id===m.id))MATERIAIS.push(m);
 MATERIAIS.find(m=>m.id==='nada').nome='Sem acessórios adicionais';

 corrigir('D2','Tempo do split-step: iniciar antes do contato e aterrissar logo depois.',e=>{
  e.objetivo='Sincronizar o split-step com a batida do adversário: iniciar o pequeno salto pouco antes do contato e aterrissar logo depois, pronto para reagir.';
  e.execucao='O professor simula e depois executa batidas. O aluno inicia um split-step curto pouco antes do contato, aterrissa logo depois e dá o primeiro passo na direção da bola. Sem bola no começo, apenas para ajustar o tempo.';
  e.passos[2]='Inicie o pequeno salto pouco antes do contato e aterrisse logo depois, quando a direção da bola ficar clara.';
  e.prog.topo='Vídeo no celular: observe se o salto começa antes do contato e se a aterrissagem permite reagir logo depois.';
  e.prog.construcao='Dentro de troca viva: confira se o aluno está no ar perto do contato e aterrissa em tempo de sair para a bola.';
  e.sucesso='8 de 10 splits com início antes do contato e aterrissagem logo depois, permitindo o primeiro passo na direção da bola.';
  e.fig.nota='Split-step curto iniciado antes do contato; aterrissagem logo depois e primeiro passo na direção da bola.';
  pecas(e,'aluno')[0][3]='split sincronizado';
 });
 corrigir('D4','Deslize controlado; retirar a orientação de travar o pé ou o joelho.',e=>{
  substituir(e,'o pé de fora travando','o apoio externo controlando a freada');substituir(e,'o pé de fora trava','o apoio externo controla a freada');substituir(e,'Pé de fora travando','Controle do apoio externo');
  e.execucao='Deslocamento lateral progressivo, deslize curto e controlado até a referência, estabiliza por 2 segundos e recupera. Mantenha o joelho flexionado e alinhado ao pé; não bloqueie o joelho nem force um travamento brusco.';
  e.passos[2]='Na chegada, deslize de forma controlada, mantendo o joelho flexionado e alinhado ao pé.';
  e.dica='Comece com velocidade e amplitude baixas. Aumente apenas quando o aluno conseguir frear e estabilizar sem perder o alinhamento.';
 });
 corrigir('F01','Incluir o rodo necessário para alisar o saibro.',e=>e.mat.push('rodo'));
 corrigir('F02','Medicine ball sem raquetes e parceiros frente a frente no mesmo lado da rede.',e=>{
  e.fig.el=[['aluno',0,11.4,'arremessa','esperaLivre'],['colega',0,8.4,'recebe','esperaLivre'],['bola',0,11,0,8.8,0,'medicine ball'],['texto',0,13,'3 séries de 6 por lado']];
  e.montagem='Medicine ball leve, adequada ao aluno, e parede apropriada ou parceiro a aproximadamente 3 metros, no mesmo lado da rede.';
 });
 corrigir('F03','Apoio único é um exercício de equilíbrio, não uma obrigação em toda bola aberta.',e=>{
  e.objetivo='Desenvolver equilíbrio unipodal e controle das aterrissagens, úteis nas bolas abertas e na recuperação.';
  e.dica='O apoio depende da bola e do deslocamento. Este exercício treina a estabilidade em um pé; no jogo, use os apoios necessários para bater e recuperar com controle.';
  e.prog.ascensao='Aumente gradualmente a precisão do salto e da aterrissagem, sempre de olhos abertos. Olhos fechados apenas no equilíbrio estático, com supervisão.';
  e.prog.topo='Após a aterrissagem controlada, receba uma bola facilitada; use um ou dois apoios conforme a bola exigir.';
  e.passos[4]='Avance para bola facilitada apenas depois de estabilizar. Saltos e batidas sempre com os olhos abertos.';
  e.dificultar=['Aterrissar em uma marca menor, com controle','Salto lateral um pouco maior, sem perder o eixo','Bola facilitada depois da estabilização'];
 });
 corrigir('F05','Bolas de cesta entram no Ascensão; a corda não usa raquete.',e=>{e.passos[4]='No Ascensão, depois do bloco 3, acrescente 4 bolas de cesta. No Construção, cobre apenas aterrissagem estável e joelhos flexionados.';e.mat.push('cesta');livres(e);});
 corrigir('F08','Base aberta sem bloqueio brusco do apoio; backhand de uma mão admite adaptação.',e=>{
  substituir(e,'pé de fora travando','apoio externo estável');substituir(e,'pé de fora travar','apoio externo estabilizar');substituir(e,'Pé de fora travando','Apoio externo estável');
  e.prog.ascensao='Forehand e backhand de duas mãos em bolas largas, sem aviso. No backhand de uma mão, escolha uma base que preserve o equilíbrio e o espaço de contato.';
  e.passos[1]='No forehand, treine a base aberta: carregue o apoio externo com o joelho flexionado, gire e recupere sem travá-lo.';
  pecas(e,'marca')[0][3]='apoio externo estável';
 });
 corrigir('F11','Peso na parte anterior do pé, sem exigir apoio apenas nos dedos.',e=>substituir(e,'ponta do pé','parte anterior do pé'));
 corrigir('F12','Definir o resultado quando um ou os dois esquecem o split.',e=>{e.execucao+=' O primeiro split omitido encerra o ponto e dá o ponto ao adversário. Se a omissão for simultânea, repita o ponto.';e.passos[2]='O primeiro split omitido encerra o ponto: ponto do adversário. Se ambos omitirem ao mesmo tempo, repita.';});
 corrigir('D7','Incluir a cesta usada nas progressões com bola.',e=>e.mat.push('cesta'));
 corrigir('M01','Conferir a preparação em sombra ou vídeo; não congelar durante uma bola viva.',e=>{
  e.execucao='Faça primeiro a sequência sem bola, congelando no penúltimo passo para conferir a preparação. Depois lance a bola e deixe completar o golpe, sem interromper o deslocamento. Confira a preparação por observação ou vídeo.';
  e.passos[3]='Sem bola, congele no penúltimo passo e confira. Com bola, deixe terminar o golpe e revise entre as repetições.';
  e.prog.construcao='O aluno congela em sombra ao comando foto; depois repete com bola, sem parar o movimento.';e.prog.ascensao='Em troca viva, confira a preparação por vídeo ou observação e comente entre os ralis.';
  e.dificultar[0]='Conferir em troca viva, sem interromper o movimento';e.sucesso='Em 5 observações consecutivas, a preparação começa durante o deslocamento nas 5.';
  e.fig.nota='Preparação durante o deslocamento. Confira a parada apenas sem bola; a bola viva segue até o fim.';
  e.fig.el.push(['prof',-4.6,5,'alimenta de fora do corredor','espera']);
 });
 corrigir('M02','Exemplo de bissetriz: bola cruzada profunda e recuperação deslocada para o lado correto.',e=>{
  e.fig.el=[['cone',-1.2,12.4,''],['cone',0,12.4,''],['cone',1.2,12.4,'espera neste exemplo'],['aluno',2.6,10.4,'','espera'],['prof',-3.4,-10.6,'responde do canto','espera'],['bola',2.6,10.2,-3.4,-9.8,0,'cruzada profunda'],['mov',2.6,10.6,1.2,12.2,0,'recompõe']];
  e.passos[3]='Observe de onde o adversário responderá. Escolha a espera que divide os ângulos disponíveis, ajustando também a profundidade.';
  e.execucao='Troca viva. Depois de cada bola, recupere para o cone que melhor cobre as respostas possíveis do adversário. A referência é a posição de contato dele e os ângulos disponíveis, não apenas o nome cruzada ou paralela. Explique primeiro; depois peça que o aluno escolha.';
 });
 corrigir('M04','Espelho com participantes frente a frente, não lado a lado.',e=>{e.fig.el=[['aluno',0,11.2,'comanda','esperaLivre'],['colega',0,8.2,'espelha','esperaLivre'],['mov',-1.6,11.2,1.6,11.2,0,'desloca lateralmente'],['mov',-1.6,8.2,1.6,8.2,0,'espelha'],['texto',0,13,'30 segundos e troca']];});
 corrigir('M05','Margem medida acima da fita da rede, não acima de metade da altura da rede.',e=>{e.sucesso='8 de 10 recuos em diagonal, de lado e com a bola à vista; devolução profunda com margem de 0,8 a 1,5 m acima da fita da rede.';e.fig.nota='Recuo em diagonal, de lado, mantendo a bola à vista; defesa alta e profunda.';});
 corrigir('M06','O alvo cruzado muda conforme o lado de contato.',e=>{substituir(e,'um alvo fixo (o cruzado)','o alvo cruzado correspondente ao lado de contato');});
 corrigir('M07','Distância confortável não exige cotovelo travado nem reproduz a distância da raquete.',e=>{
  substituir(e,'braço esticado e confortável','braço em alcance confortável, sem travar o cotovelo');substituir(e,'Braço esticado confortável','Alcance confortável, cotovelo solto');substituir(e,'braço confortavelmente esticado','braço em alcance confortável');
  e.dica='A mão ajuda a perceber o espaço lateral. Ao entrar a raquete, ajuste a distância para o comprimento dela e para o tipo de golpe; não imponha braço totalmente reto.';
  e.erros[2]='Travar o cotovelo para alcançar a bola';e.kids='Braço de robô com articulação: encontre a bola ao lado do corpo sem encolher o espaço nem travar o cotovelo.';
  pecas(e,'marca')[0][3]='alcance confortável, ao lado';
 });
 corrigir('M09','Elástico adequado com retorno ativo; retirar ancoragem distante no poste da rede.',e=>{
  e.montagem='Elástico próprio para tração na cintura, fixado conforme o fabricante a um ponto estável ou segurado por parceiro treinado atrás do aluno. Deslocamento curto, resistência leve e área livre.';
  e.execucao='O aluno desloca-se lateralmente contra resistência leve, estabiliza a base e faz uma sombra. Retorna ativamente com passos controlados, sem deixar o elástico arrastá-lo. Séries de 30 segundos por lado, com descanso e redução da resistência se perder a postura.';
  e.passos=['Confira a fixação, o limite de alongamento e o espaço livre. Use resistência leve.','Desloque lateralmente em amplitude curta, contra a resistência.','Estabilize a base e faça uma sombra de golpe.','Retorne ativamente, controlando os passos e a tensão.','Séries de 30 segundos por lado, com descanso entre elas.'];
  e.foco[3]='Retorno ativo e controlado';e.dica='A resistência auxilia a percepção da recuperação, mas o aluno controla a volta. Alivie a tensão se o tronco perder o eixo.';e.mat.push('cesta');
  e.fig.el=[['aluno',0,11.2,'','espera'],['prof',0,13.8,'segura o elástico','esperaLivre'],['mov',0.2,11.2,2.2,11.2,0,'contra resistência leve'],['mov',2.2,11.5,0.4,11.5,0,'retorno ativo'],['texto',0,9,'fixação próxima e apropriada']];e.fig.nota='Resistência leve na cintura, com parceiro atrás. Deslocamento curto e retorno ativo, sem ser arrastado.';
 });
 corrigir('M10','Descanso e dosagem por nível no exercício com fadiga.',e=>{e.execucao+=' Descanse 60 a 90 segundos entre rodadas. No Construção, use 90 segundos e 2 bolas finais; mantenha a qualidade do apoio.';e.passos[4]='Duas rodadas, com 60 a 90 segundos de descanso. No Construção: 90 segundos + 2 bolas; no Topo, acrescente um ponto.';e.dificultar[2]='Duas rodadas com o descanso mantido';e.sucesso='As bolas finais previstas para o nível saem com base estável e caem depois da linha de saque.';});
 corrigir('M11','Conversa e alongamento sem raquetes.',livres);
 corrigir('FH1','Direção do forehand depende também da face e do caminho da raquete.',e=>{e.erro='Paralela involuntária: confira o espaço de contato, o equilíbrio, a face da raquete e o caminho do golpe.';e.dica='Se a direção sair do corredor, confira pés, distância de contato e face da raquete. Uma base fechada, por si só, não determina uma paralela.';e.erros[1]='Espaço de contato insuficiente';});
 corrigir('FH2','Contorno, alimentação e saída do inside-out no mesmo ponto de contato.',e=>{pecas(e,'mov')[0].splice(1,5,-0.6,11.4,-1.8,10.2,0);pecas(e,'bola')[1].splice(1,5,-0.6,9.6,3.2,-9.2,0);e.erros[2]='Contornar uma bola apertada, sem tempo para montar a base';e.prog.topo='Em ponto valendo, contorne a bola do meio quando houver tempo e equilíbrio para manter a recuperação.';});
 corrigir('FH3','Alturas adaptadas à bola, com margem na bola de ataque e sem rigidez na face.',e=>{e.execucao='Três séries de 8: defesa alta e profunda, bola neutra com margem e ataque mais baixo, ainda com margem segura sobre a fita. A corda é uma referência de altura, não uma obrigação para todas as bolas. Nomeie a intenção antes de bater.';e.passos[3]='Série 3: trajetória mais baixa para atacar uma bola adequada, mantendo margem sobre a fita.';e.dica='A altura depende do caminho da raquete, da orientação da face e do efeito. Ajuste em conjunto, sem compensar com um movimento brusco do punho.';});
 corrigir('FH4','Topspin profundo: alvo e seta no fundo; remover erro duplicado.',e=>{pecas(e,'bola')[0].splice(3,2,-3.2,-9.4);pecas(e,'cone')[0].splice(1,2,-3.6,-10.4);e.erros=[...new Set(e.erros)];e.erros.push('Efeito sem profundidade');});
 corrigir('FH5','Bola alta aceita bases diferentes; bloqueio defensivo deve buscar profundidade.',e=>{substituir(e,'devolver de bloqueio, curto e com efeito','devolver com preparação compacta e margem, buscando profundidade');e.dica='Escolha a base conforme o tempo e a posição da bola. Uma base aberta ou semiaberta pode ajudar; o essencial é preservar espaço de contato, equilíbrio e recuperação.';e.foco[1]='Base adequada ao tempo e à altura da bola';pecas(e,'mov')[0][3]=4.4;pecas(e,'mov')[0][4]=12.6;});
 corrigir('FH6','Separar a regra de treino de uma proibição universal de deixadinhas.',e=>{e.execucao='Nesta atividade, priorize tentativas de dentro da quadra e com contato confortável, na cintura ou acima. No Ascensão, série de 8 nessas condições. No Topo, compare com 8 em condições menos favoráveis e depois aplique em pontos, cobrindo a resposta.';e.passos[3]='No Topo, compare com 8 tentativas em condições menos favoráveis; no Ascensão, mantenha apenas as favoráveis.';e.dica='Posição dentro da quadra, contato confortável e adversário distante favorecem a deixadinha. São critérios desta progressão, não uma proibição de outras soluções táticas.';e.dificultar[0]='Comparar condições de contato menos favoráveis';});
 corrigir('FH7','Escolha da passada pelo espaço livre; não por regras fixas sobre a posição do voleador.',e=>{e.montagem='Professor ou parceiro do outro lado, perto da rede, alimentando uma bola controlada. Aluno no fundo. Cesta fora da área de deslocamento.';e.execucao='O jogador da rede varia sua posição. O aluno observa o corredor livre e escolhe passada paralela, cruzada, bola baixa nos pés ou lob. O lob é uma opção quando há espaço acima do alcance do adversário. Séries de 6 por situação, depois pontos.';e.passos[1]='Observe qual corredor ficou livre: paralelo ou cruzado.';e.passos[2]='Se não houver passagem limpa, considere bola baixa nos pés para preparar a próxima.';e.passos[3]='Use o lob quando houver espaço acima do alcance do voleador e condições de executá-lo.';});
 corrigir('FH8','A defesa cruzada profunda deve cair além da linha de saque.',e=>{pecas(e,'bola')[1][4]=-9.4;substituir(e,'Séries de 6 por lado','Séries de 6 no lado do forehand');});
 corrigir('FH11','A brincadeira da porta não pode induzir contato atrás da referência.',e=>{e.kids='Porta mágica: encontre a bola na linha marcada pelo cone ou à frente dela, mantendo o cone fora do caminho dos pés.';});
 corrigir('FH12','Percentuais de esforço são percebidos; retirar o rendimento supostamente universal de 85–90%.',e=>{e.execucao='Quatro séries de 10 forehands com esforço percebido de 60%, 75%, 90% e 100%, mantendo o mesmo alvo. Registre acertos e qualidade da bola. Compare os resultados para escolher uma intensidade de jogo adequada; esses percentuais não medem a velocidade real da raquete.';e.passos[0]='Quatro séries de 10: esforço percebido de 60%, 75%, 90% e 100%, sem perder o controle.';e.passos[3]='Compare os resultados reais das quatro séries; não há um percentual ótimo universal.';e.sucesso='O aluno identifica, pelos acertos e pela qualidade da bola, qual intensidade percebida oferece o melhor controle para este alvo.';pecas(e,'zona')[0].splice(1,4,-2.0,-8.4,4,4.4);pecas(e,'bola')[0].splice(3,2,-2,-8.4);});
 corrigir('BH1','Backhand de duas mãos com extensão natural dos braços, sem fixar os cotovelos ao peito.',e=>{e.execucao='Séries de 10 backhands cruzados. Inicie pela preparação do corpo e mantenha os braços coordenados com a rotação. Preserve espaço de contato e permita a extensão natural dos braços, sem colar ou travar os cotovelos.';e.passos[3]='Mantenha espaço entre braços e tronco, permitindo extensão natural no contato e na terminação.';e.foco[1]='Espaço de contato e extensão natural dos braços';e.dica='Observe se o corpo prepara o golpe e se os braços têm espaço para avançar. A distância dos cotovelos ao peito varia durante o movimento.';e.fig.nota='Backhand de duas mãos: preparação do corpo, contato à frente e braços com espaço para avançar.';pecas(e,'cone')[0][1]=-3;});
 corrigir('BH2','A faixa profunda indicada na montagem tem exatamente os últimos 2 metros.',e=>pecas(e,'zona')[0].splice(2,3,-10.885,3.0,2));
 corrigir('BH3','A seta de avanço representa a solução 3; recuo em diagonal.',e=>{pecas(e,'mov')[0][3]=-4.4;pecas(e,'mov')[1][6]='3. avança e bate na subida';});
 corrigir('BH7','Mudança para paralelo não exige universalmente contato mais à frente ou base mais fechada.',e=>{e.execucao='Troca cruzada de backhand. Ao comando vira, escolha uma bola com tempo e equilíbrio para mudar ao corredor paralelo. Ajuste a face e o caminho da raquete mantendo contato confortável à frente do corpo; a base depende da bola. Séries de 8 mudanças.';e.passos[2]='Mantenha contato confortável à frente e ajuste face e caminho da raquete. Evite mudar em bola profunda e apertada.';e.foco[0]='Espaço e tempo de contato na mudança';e.foco[1]='Base equilibrada, adequada à bola';pecas(e,'bola')[1][3]=-3;pecas(e,'bola')[1][5]=0;});
 corrigir('BH8','Duração coerente com o título de 20 minutos.',e=>e.min=20);
 corrigir('BH9','Parada para conferir contato apenas em sombra; bola viva termina o gesto.',e=>{e.execucao='Use um cone fora do caminho dos pés como referência à frente. Confira a posição numa sombra sem bola; depois faça bolas facilitadas sem interromper o golpe. Mostre a relação entre cone, bola e mão entre as repetições ou por vídeo.';e.passos[2]='Sem bola, pare a sombra no contato e confira. Com bola, deixe completar o gesto.';e.kids='Porta do backhand: encontre a bola na linha do cone ou à frente dela; o cone fica fora do caminho dos pés.';});
 corrigir('BH12','Unificar alvo, montagem e sucesso nos últimos 3 metros.',e=>{substituir(e,'últimos 2 m','últimos 3 m');pecas(e,'zona')[0].splice(2,3,-10.385,3.4,3);});
 corrigir('BH13','Identificar os alvos pelo golpe de quem bate.',e=>{pecas(e,'zona')[0][5]='forehand cruzado';pecas(e,'zona')[1][5]='backhand cruzado';});
 corrigir('D16','Etapa com a mão em bola adaptada lenta; professor pode usar raquete.',e=>{e.objetivo='Construir o voleio pela posição, pelo deslocamento e pelo contato à frente, antes de acrescentar a raquete.';e.dica='A etapa com a mão usa bola adaptada lenta. Depois acrescente a raquete e mantenha o ajuste dos pés e o contato à frente.';e.mat.push('adaptada');pecas(e,'prof')[0][4]='espera';e.passos[0]='Aluno sem raquete; professor envia bolas adaptadas lentas e controladas, do outro lado.';e.foco[0]='Passo de ajuste coordenado com o contato';});
 corrigir('R01','Split sincronizado com a batida, e alvos de approach/voleio no lado adversário.',e=>{
  e.objetivo='Integrar approach profundo, avanço com split sincronizado à resposta do adversário e voleio no espaço.';
  e.montagem='Cone na meia-quadra como referência de avanço, sem impor o ponto exato do split. Professor do outro lado, com cesta; alvos no fundo e no ângulo adversário.';
  e.execucao='Receba uma bola curta, ataque de approach paralelo e profundo e avance. Inicie o split pouco antes da batida do adversário e aterrisse logo depois, onde estiver; o cone é apenas referência. Resolva a bola seguinte com voleio em diagonal ou defesa do lob. Séries de 6.';
  e.passos[0]='Cone na meia-quadra apenas como referência do avanço; alvos do outro lado.';e.passos[3]='Avance e sincronize o split com a batida do adversário, sem esperar chegar ao cone.';e.foco[0]='Split sincronizado com a resposta';e.sucesso='5 de 6 sequências com split sincronizado à resposta e voleio dentro da quadra.';e.erro='Avançar sem sincronizar o split com a resposta e chegar perto demais da rede.';e.dica='Faça o split no tempo da resposta, mesmo se ainda estiver na transição. Depois do voleio, ajuste a posição para a próxima bola.';
  e.fig.el=[['prof',-1.2,-11.2,'cesta / resposta','espera'],['bola',-1.2,-10.8,-1.2,5.2,0,'bola curta'],['aluno',0,11.2,'','espera'],['mov',0,11,-1.2,5.4,0,'entra'],['bola',-1.2,5.2,-1.2,-9.4,0,'approach paralelo'],['cone',-0.6,5,'referência de avanço'],['mov',-1.2,5.4,-0.6,2.8,0,'avança e faz split no contato'],['zona',3,-3.2,2,2.4,'voleio em diagonal']];e.fig.nota='Approach paralelo profundo; split no tempo da resposta e voleio no lado adversário.';
 });
 corrigir('R06','Mostrar os dois deslocamentos da dupla.',e=>e.fig.el.push(['mov',1.8,4,4.2,4,0,'acompanha']));
 corrigir('R09','Participantes a 4 metros, conforme a montagem.',e=>{pecas(e,'colega')[0][2]=-2;pecas(e,'bola')[0][2]=-1.8;pecas(e,'bola')[1][4]=-1.6;});
 corrigir('R11','Approach paralelo no mesmo corredor; escolha tática admite exceções.',e=>{pecas(e,'bola')[1][3]=-1.4;pecas(e,'bola')[1][4]=-9.4;pecas(e,'bola')[1][5]=0;pecas(e,'zona')[0].splice(1,4,-1.4,-9.4,2.4,3.6);e.objetivo='Treinar o approach paralelo profundo como padrão que facilita a cobertura da rede, comparando com escolhas cruzadas quando há espaço.';e.fig.nota='Approach paralelo profundo como padrão desta série; compare com o cruzado conforme a posição do adversário.';});
 corrigir('R13','Fechamento sem raquetes na mesma meia-quadra.',e=>{livres(e);pecas(e,'aluno')[0][2]=7.6;pecas(e,'prof')[0][2]=5.8;});
 corrigir('D15','Referência do toss perto da linha de base, sem deslocar a queda 1,7 m para dentro.',e=>{pecas(e,'zona')[0].splice(1,4,-1,11.2,0.8,0.8);pecas(e,'bola')[0][4]=11.2;e.erros[1]='Lançamento sem controle da posição de queda';});
 corrigir('S01','Saque cruza a rede para o quadrado diagonal; evitar forçar a raquete contra as costas.',e=>{pecas(e,'bola')[0][4]=-3.8;substituir(e,'"coçar as costas" — raquete atrás da cabeça e empurra da perna','queda natural da raquete atrás do corpo, sem forçar o ombro, e impulso coordenado das pernas');e.passos[2]='Etapa 3: empunhadura continental, queda natural da raquete e subida ao contato, sem encostar a raquete nas costas nem forçar o ombro.';e.sucesso='5 saques seguidos dentro do alvo, com gesto adequado ao nível: por baixo no Base, quando necessário, ou gesto completo no Impulso.';});
 corrigir('S02','Quatro alvos aberto/T, dois por quadrado; saque sempre na diagonal.',e=>{e.montagem='Quatro alvos: aberto e T em cada quadrado de saque. Contador. Alterne o lado de onde saca, acertando o quadrado diagonal correspondente.';e.passos[0]='Quatro alvos: aberto e T em cada quadrado de saque, dois alvos por lado.';e.fig.el=[['aluno',-1.6,12.3,'saca deste lado','espera'],['zona',3.2,-4.8,1.4,2,'aberto'],['zona',0.9,-4.8,1.4,2,'T'],['zona',-3.2,-4.8,1.4,2,'aberto — outro lado'],['zona',-0.9,-4.8,1.4,2,'T — outro lado'],['bola',-1.5,11.4,3.2,-4.8,0,'quadrado diagonal'],['bola',-1.5,11.4,0.9,-4.8,0,'']];e.fig.nota='Aberto e T nos dois quadrados. As setas mostram o saque de um lado; alterne a posição para usar o outro quadrado.';});
 corrigir('S03','Alvo no quadrado diagonal; corda ajustável para o topspin.',e=>{pecas(e,'zona')[0][1]=2;pecas(e,'bola')[0][3]=2;e.montagem='Alvo no quadrado diagonal. Para o topspin, use corda opcional como referência de margem, ajustada à altura e ao nível; no slice, priorize efeito e margem segura, sem impor a mesma altura.';e.passos[0]='Alvo no quadrado diagonal. Corda opcional ajustável como referência para o topspin.';e.passos[2]='No topspin, busque margem sobre a corda ajustada; no slice, margem segura sobre a fita e efeito.';e.sucesso='8 de 10 segundos saques com efeito, margem segura e quique no quadrado diagonal.';e.execucao='Séries de 10 segundos saques com efeito, usando topspin ou slice. No topspin, use a corda ajustada como referência de margem; no slice, confira margem segura sobre a fita. Conte apenas os que caem no quadrado diagonal.';e.fig.nota='Segundo saque com efeito e margem, sempre no quadrado diagonal.';pecas(e,'corda')[0][1]='referência ajustável';});
 corrigir('S04','Dupla falta valendo dois pontos é regra de treino; comparação deve usar a mesma quantidade de games.',e=>{e.execucao+=' Esta é uma regra de treino: conceda dois pontos consecutivos ao recebedor, encerrando o game assim que ele for ganho. Compare sessões com a mesma quantidade de games ou use taxas por ponto.';e.prog.ascensao='4 games; meta de no máximo 1 dupla falta no bloco, registrando também quantos pontos de saque foram jogados.';e.sucesso='Compare sessões equivalentes: reduza a taxa de duplas faltas mantendo ou melhorando o percentual de primeiro saque; registre os games ganhos.';});
 corrigir('S05','Saque aberto no quadrado diagonal e forehand no espaço do lado oposto.',e=>{pecas(e,'bola')[0][3]=3.2;pecas(e,'prof')[0][1]=3.4;pecas(e,'bola')[1][1]=3.4;pecas(e,'mov')[0][3]=-0.4;pecas(e,'zona')[0][1]=-3.2;});
 corrigir('S06','Espera da devolução atrás da área de saque e saque no quadrado diagonal.',e=>{pecas(e,'prof')[0][2]=-12.3;pecas(e,'cone')[0].splice(1,2,-3.4,10.4);pecas(e,'cone')[1].splice(1,2,-3.4,11.9);pecas(e,'cone')[2].splice(1,2,-3.4,13.4);pecas(e,'aluno')[0].splice(1,2,-3.4,11.9);pecas(e,'bola')[0][3]=-3;});
 corrigir('S09','Vídeo usado na progressão Topo deve constar dos materiais.',e=>e.mat.push('celular'));
 corrigir('S12','Saque de pressão no quadrado diagonal.',e=>pecas(e,'bola')[0][3]=2.6);
 corrigir('S13','Alvo no quadrado diagonal e comparação em pontos percentuais.',e=>{pecas(e,'zona')[0][1]=2.4;pecas(e,'bola')[0][3]=2.4;substituir(e,'abaixo de 20%','de no máximo 20 pontos percentuais');e.execucao+=' Descanse entre as rodadas. Compare a queda em pontos percentuais: de 80% para 60% são 20 pontos percentuais.';});
 corrigir('S14','O saque não é o único golpe que pode ser treinado sozinho.',e=>{e.dica='O lançamento e a sombra do saque podem ser treinados sem parceiro. Combine uma tarefa concreta que caiba na rotina do aluno e confira na aula seguinte.';});
 corrigir('D10','A bissetriz do exemplo com adversário no canto esquerdo desloca a espera para a direita.',e=>{pecas(e,'cone')[0][3]='';pecas(e,'cone')[1][3]='espera deste exemplo';pecas(e,'mov')[0][3]=1.4;pecas(e,'mov')[0][5]=0;});
 corrigir('D17','Definir quando a troca restrita libera a quadra inteira.',e=>{e.execucao='Comece com pelo menos 3 trocas cooperativas dentro do corredor cruzado. Depois, quem receber bola curta ou fraca pode mudar a direção; essa primeira mudança libera o ponto para a quadra inteira. Definir antes das 3 trocas perde o ponto.';e.passos[1]='Comece com pelo menos 3 trocas cooperativas dentro do corredor cruzado.';e.passos[2]='Depois das 3 trocas, uma bola curta ou fraca permite mudar a direção; a mudança libera a quadra inteira.';});
 corrigir('D18','Bola neutra também precisa de profundidade; separar alvos de treino de regras táticas universais.',e=>{e.montagem='Marque alvos do outro lado: fundo para construir, meio profundo para neutralizar e ângulo curto para definir quando a bola recebida permitir. Esses alvos são referências desta tarefa.';e.passos[0]='Marque fundo (constrói), meio profundo (neutraliza) e ângulo curto (define quando houver oportunidade).';e.dica='A intenção depende também da posição do adversário e da bola recebida. Uma bola curta no meio pode entregar o ataque; neutralizar pede margem e profundidade.';pecas(e,'zona')[0].splice(2,3,-10.6,7.2,2.2);pecas(e,'zona')[1].splice(2,3,-8.1,3.4,2.4);});
 corrigir('D19','Pro-set termina aos 8 games com vantagem; reservar duração compatível.',e=>{e.min=60;e.minFaixa='40–70';e.montagem+=' Vence quem fizer 8 games com dois de vantagem; em 8–8, tiebreak a 7 com dois de vantagem. Reserve um bloco próprio para completar.';e.passos[2]='Pro-set até 8 games, com dois de vantagem; em 8–8, tiebreak a 7, com dois de vantagem.';e.dica='O contador mostra quantas vezes o tema foi aplicado. Para saber em qual game ele caiu, registre também as marcas ao final de cada game.';e.mat.push('cartao');});
 corrigir('D21','Penalidade da rotina sem reverter retrospectivamente um ponto já concluído.',e=>{e.execucao='Pontos valendo. Entre pontos, o aluno percorre as marcas da rotina dentro de 20 segundos: respiração, decisão e posição. Uma omissão ou atraso concede um ponto de penalidade ao adversário antes do próximo ponto, uma única vez. No Construção, use dois passos sem cronômetro.';e.passos[4]='Uma omissão ou atraso concede um ponto de penalidade antes do próximo ponto; não reverta o resultado anterior. No Construção, dois passos sem cronômetro.';});
 corrigir('D23','Um set completo precisa de bloco maior e cartão para registro.',e=>{e.min=45;e.minFaixa='30–60';e.mat.push('cartao');e.montagem+=' Reserve um bloco próprio para completar o set; mantenha a regra de contagem combinada antes do início.';});
 corrigir('D24','Mentoria mantém supervisão do professor e usa cartão de observação.',e=>{e.dificultar[2]='Menos lembretes do professor, mantendo a supervisão';e.mat.push('cartao');});
 corrigir('T01','Duas voltas de quatro estações de 90 segundos totalizam 12 minutos, mais transições.',e=>{e.min=14;e.minFaixa='12–15';e.passos[1]='Aproximadamente 90 segundos por estação; no Base, conduza sem exigir cronômetro.';});
 corrigir('T03','Conversa de fechamento sem raquetes.',livres);
 corrigir('R14','Passagem para voleios apenas no Impulso; Base mantém o quique.',e=>{e.passos[3]='No Base, mantenha o quique. No Impulso, quando estabilizar, passe à troca sem quique.';});
 corrigir('R15','Retorno de lado controlado, sem corrida rápida andando para trás.',e=>{e.execucao='Sem bola, corra para a frente, faça um split curto na linha de saque e toque a faixa com cuidado. Volte de lado, em diagonal, com passos controlados e mantendo a rede à vista. Séries de 6 idas; não corra para trás de peito aberto.';e.passos[3]='Volte de lado, em diagonal e com passos controlados, mantendo a rede à vista.';e.foco[1]='Retorno lateral controlado';e.fig.nota='Sem bola: ida até a faixa, parada na linha de saque e retorno de lado, controlado.';pecas(e,'mov')[0][4]=0.6;pecas(e,'mov')[1].splice(1,5,0.6,0.8,2.0,11.4,0);pecas(e,'mov')[1][6]='volta de lado';});
 corrigir('R16','Na mini-quadra todos já estão à frente da linha de saque; definir uma linha de ataque própria.',e=>{e.montagem='Mini-quadra ou quadra reduzida; bola adaptada. Na mini-quadra, marque uma linha de ataque a 3 m da rede em cada lado; na quadra maior, use a linha de saque.';e.execucao='Pontos valendo: vitória com o jogador à frente da linha de ataque vale 2; as demais vitórias valem 1. Na mini-quadra, a linha de ataque fica a 3 m da rede. Na quadra maior, use a linha de saque. Narre o placar e incentive uma aproximação equilibrada.';e.passos[0]=e.montagem;e.passos[2]='Vitória à frente da linha de ataque vale 2; atrás dela, vale 1.';pecas(e,'zona')[0].splice(2,3,4.8,6,2.4);e.fig.nota='Na mini-quadra: vitória entre a rede e a linha de ataque de 3 m vale 2. Atrás, vale 1.';});
 corrigir('S15','Arremessos controlados; materiais e figura sem raquete.',e=>{e.mat=e.mat.filter(x=>x!=='nada');e.mat.push('bolas');e.montagem='Uma bola por aluno, corredor livre de arremesso e alvo. Elástico leve opcional. Faça arremessos progressivos, sem buscar distância máxima.';e.passos[1]='Oito arremessos controlados por lado, com corpo de lado, em corredor livre.';e.kids='Concurso de precisão num alvo, com distância adequada à idade.';livres(e);});
 corrigir('S16','Sacador com raquete e atrás da linha; pegar a bola depois do quique, fora do quadrado.',e=>{pecas(e,'prof')[0][2]=-12.3;pecas(e,'prof')[0][4]='espera';pecas(e,'mov')[0][4]=9.6;pecas(e,'marca')[0][2]=9.2;pecas(e,'marca')[0][3]='pega depois do quique';e.fig.el.push(['bola',-1.8,5.4,-1.8,9.2,0,'depois do quique']);e.dificultar[2]='Saque leve variando direção, mantendo a pegada confortável';});
 corrigir('BH15','Aproximar professor e aluno para os 4 metros descritos.',e=>{pecas(e,'prof')[0][2]=-2;pecas(e,'prof')[0][4]='esperaLivre';pecas(e,'aluno')[0][2]=2;pecas(e,'bola')[0].splice(2,3,-1.8,-2.2,1.6);pecas(e,'marca')[0][2]=1.2;});
 corrigir('M13','Mini-tênis com jogadores atrás da linha de saque; metas por nível.',e=>{pecas(e,'aluno')[0][2]=6.8;pecas(e,'colega')[0][2]=-6.8;pecas(e,'zona')[0].splice(2,3,3.2,5.4,6.4);pecas(e,'bola')[0].splice(2,3,-6.4,1,4.8);pecas(e,'bola')[1].splice(2,3,6.4,-1,-4.8);e.erros[1]='Afastar-se progressivamente da linha de saque para bater mais forte';e.passos[2]='Meta: 5 trocas no Base, com dois quiques se necessário; 10 do Impulso em diante.';e.sucesso='Meta do nível atingida dentro dos quadrados: 5 no Base ou 10 do Impulso em diante, antes de ir ao fundo.';});
 corrigir('FH15','Parede no mesmo lado do aluno; não trocar bolas através da rede; metas 10/20/30 por nível.',e=>{e.fig.el=[['zona',0,2.0,8,0.6,'parede / frontão'],['aluno',0,9,'','espera'],['bola',0,8.6,-0.2,2.4,0,'vai à parede'],['bola',0.6,2.4,0.6,8.6,0,'rebote'],['marca',0,11,'ajuste a distância'],['texto',0,13,'10 / 20 / 30 conforme o nível']];e.fig.nota='Parede representada pela faixa, no mesmo lado do aluno. A rede ao fundo não participa desta atividade.';e.sucesso='Meta do nível acima da fita: 10 bolas no Base, 20 no Impulso e 30 no Construção/Ascensão. Voleios apenas quando houver controle.';e.passos[1]='Forehands controlados: 10 no Base, 20 no Impulso ou 30 no Construção/Ascensão.';e.passos[2]='Repita a mesma meta com backhands.';e.passos[3]='Repita alternando os lados; no Base, permita dois quiques.';e.passos[4]='Acrescente voleios quando houver controle; ajuste a distância sem perder a segurança.';e.dica+=' O rebote perde velocidade; a parede não acelera a bola, mas exige preparação rápida.';});
 corrigir('S17','Montagem inicial em pé claramente identificada, apoio acolchoado e meta adaptada ao Base.',e=>{e.mat.push('colchonete');e.montagem='Colchonete para apoiar os joelhos, em superfície estável. Ajuste a distância ao nível; no Base, de dentro da quadra com alvo amplo. Cesta ao lado e movimento de ombro confortável.';e.passos[0]=e.montagem;e.sucesso='6 de 10 no alvo do nível: quadra adversária no Base ou quadrado diagonal do Impulso em diante, sem forçar o ombro.';pecas(e,'aluno')[0].splice(2,3,12.3,'posição antes de ajoelhar','espera');pecas(e,'zona')[0].splice(1,4,-2.0,-3.2,3.8,6.2);e.fig.nota='Montagem antes de ajoelhar: use colchonete e ajuste a distância. A figura em pé indica a posição inicial, não a execução.';});
 corrigir('T07','Uma bola por vez; percurso externo até a fila oposta.',e=>{e.dificultar[2]='Rotação mais rápida, mantendo uma única bola em jogo';e.fig.el.push(['mov',-5.8,9,-5.8,-12.8,0,'por fora'],['mov',-5.8,-12.8,3.6,-13.2,0,'fim da outra fila']);});
 corrigir('T08','Rodadas com raquete apenas no Impulso; professor de frente no mesmo lado.',e=>{e.passos[3]='No Base, mantenha sem raquete. No Impulso, faça a segunda rodada com raquete.';e.passos[4]='No Impulso, o vermelho vira split-step seguido do primeiro passo para o lado indicado.';e.fig.el.push(['prof',0,2.6,'comanda de frente','esperaLivre']);});
 corrigir('T09','Arremessos sem raquetes com bolas adaptadas.',e=>{livres(e);e.mat.push('adaptada');e.dificultar[2]='Precisão em alvos, mantendo mãos livres e uma bola de cada vez';});
 corrigir('T10','Travessia da raquete no mesmo lado da rede.',e=>{pecas(e,'mov')[0][4]=9;pecas(e,'mov')[0][6]='percurso no mesmo lado';});
 corrigir('T11','Saque da mini-quadra parte da linha de fundo reduzida.',e=>{pecas(e,'aluno')[0][2]=6.6;pecas(e,'colega')[0][2]=-6.6;pecas(e,'bola')[0][2]=6.2;e.execucao+=' Alterne o sacador a cada dois pontos, usando a linha de fundo da quadra reduzida; combine a regra antes da partida.';});
 corrigir('F14','A sequência direta forma o X; voltar ao centro a cada bola contradizia o desenho.',e=>{e.execucao='Alimente no padrão: fundo do forehand, curta do backhand, fundo do backhand e curta do forehand. O aluno segue diretamente ao próximo canto, recompõe a base entre contatos e volta ao centro ao fim das quatro bolas. Três séries: 4 bolas no Construção, 8 no Ascensão/Topo, com 45 segundos de descanso.';e.passos[2]='Siga diretamente ao próximo canto, estabilize o apoio a cada contato e volte ao centro ao fim do ciclo de quatro.';e.passos[3]='Três séries: 4 bolas no Construção ou 8 no Ascensão/Topo; 45 segundos de descanso.';e.foco[1]='Recomposição da base entre contatos';e.sucesso='Três séries completas na dose do nível, com as bolas de fundo além da linha de saque.';});
 corrigir('D26','Séries em múltiplos de quatro e sucesso compatível com a dose.',e=>{e.execucao='Um jogador só bate cruzado; o outro, paralelo. Quatro contatos fecham uma volta. Faça séries de 8 bolas no Ascensão ou 12 no Topo, com 30 a 60 segundos de descanso, e troque os papéis. Três séries por papel, mantendo a qualidade.';e.prog.ascensao='Séries de 8 bolas: duas voltas, cooperativas, sem alvo.';e.prog.topo='Séries de 12 bolas: três voltas, em ritmo de jogo, com bolas além da linha de saque.';e.passos[3]='8 bolas no Ascensão ou 12 no Topo; 30 a 60 segundos de descanso e troca de papéis.';e.sucesso='Duas voltas completas no Ascensão ou três no Topo, sem quebrar o padrão.';e.dificultar[0]='12 bolas por série, com qualidade mantida';});
 corrigir('D27','Dose e sucesso compatíveis com 60 segundos no Construção.',e=>{e.passos[3]='60 segundos no Construção, 90 no Ascensão/Topo; rode as posições e dê descanso ao jogador sozinho.';e.sucesso='Sustenta a duração do nível, 60 ou 90 segundos, e mantém a base nas últimas cinco bolas.';});
 corrigir('R18','Alvos dos voleios em lados opostos, sem uma zona sobre a rede.',e=>{e.fig.el=e.fig.el.filter(p=>p[0]!=='zona');e.fig.el.push(['zona',2,2.5,2,3.5,'corredor'],['zona',-2,-2.5,2,3.5,'corredor oposto']);});
 corrigir('BH16','Deixada e lob atravessam a rede em sentidos opostos.',e=>{e.montagem='Dois corredores cruzados usando a profundidade da quadra inteira. Ponto começa com deixada de dentro da quadra, em bola alimentada. Contador.';e.passos[0]=e.montagem;e.fig.el=[['aluno',1.8,6.8,'faz a deixada','espera'],['prof',-1.8,-6.8,'busca e decide','espera'],['bola',1.8,6.2,-2.6,-1.8,0,'1. deixada'],['mov',-1.8,-6.6,-2.6,-2.2,0,'busca'],['bola',-2.6,-1.8,2.2,10.6,0,'2. lob de resposta'],['mov',1.8,6.6,2.2,2.8,0,'cobre a resposta']];e.fig.nota='Deixada para o lado adversário; o jogador que busca pode devolver curta ou lobar de volta por cima da rede.';});
 corrigir('FH17','Contorno põe o corpo ao lado da bola; inside-in conserva o corredor.',e=>{pecas(e,'mov')[0].splice(3,3,-3.6,10.4,0);for(const b of pecas(e,'bola').slice(1)){b[1]=-2.6;b[2]=9.6;}pecas(e,'bola')[1][3]=-2.6;pecas(e,'bola')[1][5]=0;pecas(e,'zona')[0][1]=-2.6;});
 corrigir('FH19','Altura oferece tempo, mas não há ganho fixo de um segundo.',e=>{e.dica='Uma defesa alta e profunda pode dar mais tempo para recuperar. O ganho depende da velocidade, do efeito e da posição do adversário; mantenha altura junto com profundidade.';});
 corrigir('R19','Posição a um passo e meio da linha de saque e respostas atribuídas às bolas corretas.',e=>{pecas(e,'aluno')[0][2]=5.2;for(const b of pecas(e,'bola').slice(0,2))b[4]=4.8;pecas(e,'bola')[2].splice(1,2,-0.6,4.8);pecas(e,'bola')[2][6]='alta: ângulo';pecas(e,'bola')[3].splice(1,2,1.4,4.8);pecas(e,'bola')[3][6]='baixa: fundo';});
 corrigir('R20','Voleio tem avanço curto da raquete; bloco fundo deve terminar no fundo.',e=>{substituir(e,'A raquete para no contato','A raquete avança de forma curta e controlada no contato');e.passos[3]='Avanço curto e controlado, sem backswing amplo e sem forçar uma parada brusca.';e.foco[2]='Punho firme e avanço curto';e.sucesso='8 de 10 voleios de backhand dentro da quadra, com gesto compacto e base estável.';e.fig.nota='Voleio de backhand: ombro preparado, passo coordenado e avanço curto da raquete.';pecas(e,'bola')[1][4]=-9.4;});
 corrigir('R22','Jogador começa perto da rede antes de recuar para o smash.',e=>pecas(e,'aluno')[0][2]=2.8);
 corrigir('S18','Split no tempo da devolução, onde o jogador estiver, não obrigatoriamente na linha de saque.',e=>{e.objetivo='Integrar saque, avanço, split sincronizado à devolução e primeiro voleio profundo.';e.montagem='Cone na linha de saque como referência do avanço, sem impor o lugar do split. Alvo profundo do outro lado.';e.sucesso='5 de 6 primeiros voleios profundos, com split sincronizado à devolução, onde o aluno estiver na transição.';e.fig.nota='Saque, avanço e split no tempo da devolução; o cone é só referência, e o primeiro voleio busca profundidade.';});
 for(const id of ['R23','R24'])corrigir(id,'Quatro participantes exigem trio/quarteto; em dupla de alunos falta um jogador.',e=>{e.form=['trio'];e.jogadores='4 em quadra';e.montagem+=' São necessários quatro participantes: quatro alunos, ou três alunos e o professor.';});
 corrigir('R23','Tempo do poach pode variar; retirar obrigação de sair no instante exato.',e=>{e.execucao='Combine cruza ou fica antes do saque. No poach, ajuste a saída ao saque e à preparação da devolução, cruzando para interceptar sem denunciar cedo demais nem chegar atrasado. Voleie no espaço ou nos pés; o sacador cobre o lado liberado. Seis saques e depois pontos.';e.passos[2]='Ao cruzar, ajuste a saída para interceptar a devolução; voleie no espaço ou nos pés.';e.foco[1]='Tempo da saída: sem denunciar cedo ou chegar atrasado';});

 corrigir('F03','A figura em dois apoios representa a preparação, não o equilíbrio unipodal.',e=>{pecas(e,'aluno')[0][3]='posição inicial';e.fig.nota='Montagem inicial antes do equilíbrio em um pé. Execute a sequência unipodal conforme as instruções; a figura mostra a preparação.';});
 corrigir('F11','Rótulos coerentes com o peso na parte anterior do pé.',e=>{pecas(e,'aluno')[0][3]='peso na parte anterior';pecas(e,'texto')[0][3]='10 s no calcanhar · 10 s à frente';substituir(e,'ponta dos pés','parte anterior dos pés');});
 corrigir('FH1','Meta de sucesso compatível com a série e com o uso opcional da corda por nível.',e=>{e.sucesso='Impulso: 7 de 10 no corredor, sem corda. Construção: 15 trocas no corredor e acima da referência. Ascensão/Topo: 12 trocas no ritmo e na altura combinados.';});
 corrigir('BH1','Meta do Base compatível com a quadra reduzida.',e=>{e.sucesso='8 de 10 no alvo do nível, com contato à frente. No Base, quadra reduzida; no Impulso/Construção, bolas profundas além da linha de saque, com margem sobre a fita.';});
 corrigir('BH15','Manter dois toques no Base e retirar o ajuste apenas no Impulso.',e=>{e.passos[4]='Base: 20 repetições com dois toques. Impulso: 10 com dois toques e 10 com um.';});
 corrigir('S07','Meta quantitativa também no Topo.',e=>{e.prog.topo+=' Meta de 6 de 10 devoluções profundas cumprindo a intenção anunciada.';});
 corrigir('S01','Rótulo da terceira etapa coerente com a queda natural da raquete.',e=>{pecas(e,'marca')[2][3]='3. queda natural';});
 corrigir('D24','Mentor orientado para o iniciante durante a supervisão.',e=>{pecas(e,'aluno')[0][5]='frente';});
 corrigir('T06','Observador acompanha o colega no mesmo lado da quadra.',e=>{pecas(e,'colega')[0][5]='frente';});
 corrigir('R24','Interceptação começa na terceira bola, após dois contatos sem interceptar.',e=>{e.execucao=e.execucao.replace('não podem interceptar a primeira','não podem interceptar as duas primeiras');});
 corrigir('M09','Aluno voltado para a rede, com o parceiro do elástico atrás dele.',e=>{pecas(e,'aluno')[0][5]='costas';pecas(e,'prof')[0][5]='costas';});
 corrigir('T07','Retorno por fora dos postes da rede, sem atravessar a rede estendida no corredor de duplas.',e=>{
  pecas(e,'mov').forEach(p=>{if(p[1]===-5.8)p[1]=-6.8;if(p[3]===-5.8)p[3]=-6.8;});
  e.montagem+=' Demarque o retorno por fora dos postes da rede, com espaço livre para as filas.';
  e.passos[2]='Depois de bater, corre pelo lado de fora dos postes da rede para o fim da fila do outro lado.';
  e.fig.nota+=' O percurso passa por fora dos postes, sem cruzar a rede.';
 });

 /* Alvos de simples ficam dentro das linhas, sem ensinar que o corredor de
    duplas vale em simples. Faixas físicas e marcações de apoio são exceções. */
 const fisicas=new Set(['F01','D15','T01','FH15','FH18']);
 EX.filter(e=>e.id!=='D2-FH-03').forEach(e=>{
  corrigir(e.id,'Limitar os alvos de simples às linhas da quadra.',e=>{
   if(fisicas.has(e.id))return;
   pecas(e,'zona').forEach(p=>{let l=Math.max(-4.115,p[1]-p[3]/2),r=Math.min(4.115,p[1]+p[3]/2);let a=Math.max(-11.885,p[2]-p[4]/2),b=Math.min(11.885,p[2]+p[4]/2);if(p[2]<0)b=Math.min(0,b);if(p[2]>0)a=Math.max(0,a);if(Math.abs(l-(p[1]-p[3]/2))+Math.abs(r-(p[1]+p[3]/2))+Math.abs(a-(p[2]-p[4]/2))+Math.abs(b-(p[2]+p[4]/2))>1e-8){p[1]=(l+r)/2;p[2]=(a+b)/2;p[3]=r-l;p[4]=b-a;}});
  });
 });
 // Os pés dos sacadores ficam atrás da linha; o contato pode ocorrer adiante.
 for(const id of ['S01','S02','S03','S04','S05','S09','S10','S12','S13','S17','S18','R23'])corrigir(id,'Montagem do sacador atrás da linha de base.',e=>{let p=e.fig.el.find(p=>['aluno','colega'].includes(p[0])&&p[2]>11.885);if(p)p[2]=12.35;});
 corrigir('S08','Sacador atrás da linha de base.',e=>pecas(e,'prof')[0][2]=-12.35);
 // A altura real da corda é explícita; antes todas eram desenhadas a 1,75 m.
 EX.forEach(e=>{if(pecas(e,'corda').length)corrigir(e.id,'Altura da corda compatível com a indicação da ficha.',e=>pecas(e,'corda').forEach(p=>{const m=(e.montagem+' '+p[1]).match(/a (\d+(?:[.,]\d+)?) m (?:sobre|acima)/i);p[2]=m?0.914+Number(m[1].replace(',','.')):1.914;}));});
 /* A referência adicional conserva o texto aprovado; a tomada de decisão
    permite backhand no outro lado, sem impor forehand numa bola apertada. */
 corrigir('D2-FH-03','Esclarecer forehand no lado dominante e a variação de backhand no lado oposto.',e=>{e.execucao+=' Priorize o lado dominante. No lado oposto, use a variação de backhand ou contorne apenas quando houver tempo e espaço para o forehand.';e.sucesso='Em 8 de 10 bolas, manter equilíbrio, acertar além da linha de saque e recuperar a posição de espera.';e.fig.nota+=' A seta do lado oposto é a variação de backhand ou um forehand com contorno e tempo suficiente.';});
})();
