/* Protótipo visual isolado. Não integra a aplicação nem altera DB/Firebase. */
(function(){
 if(document.getElementById('vzp-abrir'))return;
 const style=document.createElement('style');style.textContent="\n#vzp-abrir{position:fixed;z-index:80;right:max(16px,calc((100vw - 520px)/2 + 16px));bottom:calc(78px + env(safe-area-inset-bottom,0px));width:54px;height:54px;border-radius:50%;border:1px solid #E8BA81;background:radial-gradient(circle at 30% 20%,#F4D997,#C96E37 56%,#2A5E43);color:#14271D;box-shadow:0 6px 24px #0008;display:flex;align-items:center;justify-content:center;padding:0}\n#vzp-abrir svg{width:25px;height:25px;stroke:#12261B}\n#vzp-fundo{display:none;position:fixed;inset:0;z-index:401;background:#04100BCD;backdrop-filter:blur(6px)}\n#vzp-fundo.on{display:flex;align-items:flex-end;justify-content:center;padding:16px 16px calc(76px + env(safe-area-inset-bottom,0px))}\n#vzp-painel{width:100%;max-width:488px;background:#112C23;border:1px solid #9B8261;border-radius:24px;padding:20px;color:#FFF;box-shadow:0 20px 60px #0008;max-height:80vh;overflow:auto;font-family:'DM Sans',sans-serif}\n#vzp-painel .vzp-cab{display:flex;align-items:center;justify-content:space-between;gap:12px}\n#vzp-painel h3{margin:0;color:#FFF;font-size:21px;font-family:'DM Sans',sans-serif}\n#vzp-painel .vzp-fechar{width:44px;height:44px;padding:0;background:#223C31;color:#FFF;border:1px solid #6A8270;border-radius:50%;font-size:23px}\n#vzp-painel .vzp-nota{color:#E0E7DD;font-size:12px;line-height:1.5;margin:8px 0 15px}\n#vzp-painel .vzp-escuta{display:flex;align-items:center;gap:12px;margin:12px 0}\n#vzp-painel .vzp-bola{width:54px;height:54px;border-radius:50%;background:radial-gradient(circle at 30% 30%,#E9E285,#C47B48 45%,#4F916D 70%,#244A3C);box-shadow:0 0 22px #D4E15725;border:1px solid #B9B47B;flex-shrink:0}\n#vzp-painel .vzp-escuta b{display:block;font-size:14px;color:#FFF}\n#vzp-painel .vzp-escuta small{display:block;font-size:12px;color:#D9E2D9;line-height:1.5}\n#vzp-painel .vzp-texto{padding:12px;border-radius:12px;background:#203D31;border:1px solid #78917A;color:#FFF;font-size:14px;line-height:1.5;margin:14px 0}\n#vzp-painel .vzp-acao{padding:14px;border-radius:14px;background:#F7F3E8;color:#253525}\n#vzp-painel .vzp-acao b{display:block;color:#253525;font-size:15px}\n#vzp-painel .vzp-acao p{color:#253525;font-size:13px;line-height:1.6;margin:6px 0}\n#vzp-painel .vzp-aviso{font-size:12px;color:#46623F;margin:0}\n#vzp-painel .vzp-botoes{display:flex;gap:8px;margin-top:16px}\n#vzp-painel .vzp-botoes button{min-height:46px;flex:1;font-size:13px;font-weight:800;border-radius:12px;padding:10px;background:#D4E157;color:#1E2A0E;border:1px solid #D4E157}\n#vzp-painel .vzp-botoes button:last-child{background:#203D31;color:#FFF;border:1px solid #78917A}\n";
 const abrir=document.createElement('button');abrir.id='vzp-abrir';abrir.type='button';abrir.setAttribute('aria-label','Ações rápidas por voz — prévia');
 abrir.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke-width="2" aria-hidden="true"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M6 10v2a6 6 0 0 0 12 0v-2M12 18v3M8 21h8"/></svg>';
 const fundo=document.createElement('div');fundo.id='vzp-fundo';
 fundo.innerHTML='<section id="vzp-painel" role="dialog" aria-modal="true" aria-labelledby="vzp-title"><div class="vzp-cab"><h3 id="vzp-title">Ações por voz</h3><button class="vzp-fechar" aria-label="Fechar prévia">×</button></div><p class="vzp-nota">Prévia visual · dados fictícios · nenhuma alteração será aplicada.</p><div class="vzp-escuta"><span class="vzp-bola" aria-hidden="true"></span><span><b>Entendi seu pedido</b><small>Confira os detalhes antes de confirmar.</small></span></div><div class="vzp-texto">“Aluno Fictício cancelou a aula de sexta às quatro da tarde.”</div><div class="vzp-acao"><b>Cancelar uma aula</b><p>Aluno Fictício<br>Sexta, 16 de outubro · 16:00</p><p class="vzp-aviso">Somente esta data. As outras semanas continuam marcadas.</p></div><div class="vzp-botoes"><button type="button" disabled>Confirmar cancelamento</button><button type="button" disabled>Corrigir pedido</button></div></section>';
 abrir.onclick=()=>fundo.classList.add('on');fundo.querySelector('.vzp-fechar').onclick=()=>fundo.classList.remove('on');
 fundo.onclick=e=>{if(e.target===fundo)fundo.classList.remove('on');};
 document.head.appendChild(style);document.body.append(abrir,fundo);
})();
